---
abstract: 'A pre-edit file backup program'
author:
  - 'Duncan Ferguson <duncan_j_ferguson@yahoo.co.uk>'
build_requires:
  English: 0
  File::Basename: 0
  File::Copy: 0
  File::Which: 0
  FindBin: 0
  Getopt::Long: 0
  POSIX: 0
  Pod::Usage: 0
  Test::More: 0.94
  Test::Trap: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-bk
provides:
  App::bk:
    file: lib/App/bk.pm
    version: 0.02
requires:
  English: 0
  File::Basename: 0
  File::Copy: 0
  File::Which: 0
  FindBin: 0
  Getopt::Long: 0
  POSIX: 0
  Pod::Usage: 0
resources:
  bugtracker: https://github.com/duncs/perl-app-bk/issues
  homepage: https://github.com/duncs/perl-app-bk
  license: http://dev.perl.org/licenses/
  repository:
    - http://github.com/duncs/perl-app-bk
version: 0.02
